#!/bin/bash

cd ~/main/ostis-web-platform/scripts

usage() {
	echo "usage: $(basename $0) [--build] [--start]"
}

# if no arguments are provided, return usage function
if [ $# -eq 0 ]; then
    usage
    exit 1
fi


for arg in "$@"; do
    case $arg in
    -b | --build)
		./build_kb
		;;
	-s | --start)
		./run_sc_server.sh | ./run_scweb.sh
		;;
    *)
        usage
        ;;
    esac
done

